services:
  backend:
    build:
      context: ./todo-app/backend
      dockerfile: dockerfile
    container_name: todo_backend
    ports:
      - "8081:8081"
    volumes:
      - ./todo-app/backend/data:/app/data
    env_file:
      - ./todo-app/backend/.env
    environment:
      - DATABASE_URL=sqlite:////app/data/todo.db
    restart: always

  frontend:
    build:
      context: ./todo-app/frontend
      dockerfile: dockerfile
    container_name: todo_frontend
    ports:
      - "8502:8501"
    environment:
      - API_URL=http://backend:8081
    depends_on:
      - backend
    restart: always